_target_: simulators.bernoulli_sir.BernSIR

name: "bern_sir"

#p_concentration_1: 3.0
#p_concentration_2: 2.0
p_lower: 0.1
p_upper: 1.0
beta_lower: 0.1
beta_upper: 1.0
gamma_lower: 0.1
gamma_upper: 1.0

population: 100

theta_dim: 3
x_dim: 12

num_bins: 10

prior_start: [0.1, 1.0, 0.001]

k_mixture: [0., 0.25, 1., 2.]