_target_: simulators.temporal_sir.TemporalSIR

name: "temp_sir"

beta_lower: 0.1
beta_upper: 1.0
gamma_lower: 0.1
gamma_upper: 1.0
#gamma_concentration: 2.0
#gamma_rate: 1.0

population: 1000

theta_dim: 2
x_dim: 12

num_bins: 10

prior_start: [0.1, 1.0]

k_mixture: [0., 0.25, 1., 2.]